

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name == 'Staging'
      config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Staging'
        config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
      end
    end
  end
end


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MWGPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MWGPay
  
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Fabric', '~> 1.7.9'
  pod 'Crashlytics', '~> 3.10.5'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'jail-monkey', :path => '../node_modules/jail-monkey'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

end
