

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    if config.name == 'Staging'
      config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Staging'
        config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
        config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
      end
    end
  end
end


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MWGPay' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MWGPay
  
  pod 'Firebase/Messaging', '~> 6.2.0'
  # pod 'Firebase/Core', '~> 6.3.0'
  # pod 'Fabric', '~> 1.7.9'
  # pod 'Crashlytics', '~> 3.10.5'

  # pod 'RNScreens', :path => '../node_modules/react-native-screens'
  # pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # pod 'jail-monkey', :path => '../node_modules/jail-monkey'

  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  # pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'
  
  # pod 'React', :path => '../node_modules/react-native'
  # pod 'yoga', :path => "../node_modules/react-native/ReactCommon/yoga"
  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
# See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS


end
